# Generated by Django 5.0.6 on 2024-06-26 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_product', '0002_product_assigned_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='assigned_user',
        ),
    ]
